name: Build and publish fleet manager

on:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: adapter_meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/ba23-robotic-fleet-management/free-fleet-rmf-adapter

      - name: Extract metadata (tags, labels) for Docker
        id: free_fleet_server_meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/ba23-robotic-fleet-management/free-fleet-server

      - name: Extract metadata (tags, labels) for Docker
        id: free_fleet_client_meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/ba23-robotic-fleet-management/free-fleet-client

      - name: Build and push rmf adapter
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile
          push: true
          target: adapter
          tags: ${{ steps.adapter_meta.outputs.tags }}
          labels: ${{ steps.adapter_meta.outputs.labels }}

      - name: Build and push free fleet server
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile
          push: true
          target: free-fleet-server
          tags: ${{ steps.free_fleet_server_meta.outputs.tags }}
          labels: ${{ steps.free_fleet_server_meta.outputs.labels }}

      - name: Build and push free fleet client
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile
          push: true
          target: free-fleet-client
          tags: ${{ steps.free_fleet_client_meta.outputs.tags }}
          labels: ${{ steps.free_fleet_client_meta.outputs.labels }}
